-- DropForeignKey
ALTER TABLE "ProcessTaskInstance" DROP CONSTRAINT "ProcessTaskInstance_instanceId_fkey";

-- DropForeignKey
ALTER TABLE "ProcessTaskTemplate" DROP CONSTRAINT "ProcessTaskTemplate_processTemplateId_fkey";

-- AlterTable
ALTER TABLE "CarModel" ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "Item" ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "Mold" ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "ProcessInstance" ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "startAt" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "endAt" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "expectedEndAt" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "updatedAt" DROP DEFAULT,
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "ProcessTaskInstance" ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "plannedStartAt" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "plannedEndAt" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "actualStartAt" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "actualEndAt" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "deadlineAt" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "updatedAt" DROP DEFAULT,
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "ProcessTaskTemplate" ADD COLUMN     "assigneeHint" TEXT,
ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "ProcessTemplate" ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "updatedAt" DROP DEFAULT,
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMP(3);

-- AddForeignKey
ALTER TABLE "ProcessTaskTemplate" ADD CONSTRAINT "ProcessTaskTemplate_processTemplateId_fkey" FOREIGN KEY ("processTemplateId") REFERENCES "ProcessTemplate"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ProcessTaskInstance" ADD CONSTRAINT "ProcessTaskInstance_instanceId_fkey" FOREIGN KEY ("instanceId") REFERENCES "ProcessInstance"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
