ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "teamsPhotoBytes" BYTEA;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "teamsPhotoContentType" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "teamsPhotoUpdatedAt" TIMESTAMP(3);
