DO $$ BEGIN
  CREATE TYPE "UserStatus" AS ENUM ('PENDING', 'ACTIVE');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "entraTenantId" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "entraOid" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "status" "UserStatus" NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "activatedAt" TIMESTAMP(3);

UPDATE "User" SET "status" = 'ACTIVE' WHERE "status" IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS "User_entraOid_key" ON "User"("entraOid");
